scoreboard players set @a potions 0
scoreboard players set @a herbology 0
scoreboard players set @a spells 0
scoreboard players set @a alchemy 0
scoreboard players set @a astronomy 0
scoreboard players set @a 3complete 0
scoreboard players set @a npc1_001 0
scoreboard players set @a 001_potions 0
scoreboard players set @a 001_herbology 0
scoreboard players set @a 001_spells 0
scoreboard players set @a 001_alchemy 0
scoreboard players set @a 001_astronomy 0
scoreboard players set @a potions_comp 0
scoreboard players set @a herbology_comp 0
scoreboard players set @a spells_comp 0
scoreboard players set @a alchemy_comp 0
scoreboard players set @a astronomy_comp 0
scoreboard players set @a classes_comp 0
scoreboard players set @a tmp 0
scoreboard players set @a 3complete_init 0
